### ISSUE TITLE
Installing poetry via pip

### ISSUE THREAD

**Issue by sadikkuzu** [Doist/todoist-api-python#175]
https://github.com/Doist/todoist-api-python/blob/cceebcf933004d6349f6475fbf342ebf3253860b/.github/workflows/ci.yml#L19-L23

Why don't you use simply: `pip install poetry` ?
As in https://python-poetry.org/docs/#installing-manually

---

Suggestion: `ci.yaml`

```yaml
name: tests

on: [pull_request, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          set -ex
          pip install --upgrade poetry
          poetry install

      - name: Test with pytest
        run: |
          set -ex
          poetry run pytest
```
